a = input('Entre com algum valor:')
print('O tipo primitivo desse valor e:', type(a))
print('O tipo so possui espaços:', a.isspace())
print ('O valor e numerico:', a.isnumeric())
print('O valor e alfabetico:', a.isalpha())
print('O valor e um alfanumerico:', a.isalnum())
print('O valor esta em maiuculo:', a.islower())
print('O valor esta em minusculo:', a.isupper())
print('O valor esta capitalizado:', a.istitle())
